Document: useless
Title: Debian useless Manual
Author: <insert document author here>
Abstract: This manual describes what useless is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/useless/useless.sgml.gz

Format: postscript
Files: /usr/share/doc/useless/useless.ps.gz

Format: text
Files: /usr/share/doc/useless/useless.text.gz

Format: HTML
Index: /usr/share/doc/useless/html/index.html
Files: /usr/share/doc/useless/html/*.html

  
