#!/usr/bin/env python
import sys
from optparse import OptionParser

# setup option parser
parser = OptionParser()

# get options and arguments
opts, args = parser.parse_args(sys.argv[1:])



COMMANDS = ['create', 'update', 'retrieve', 'addfile', 'rmfile', 'check']
# upkg create packagename [component1] [component2] [...]

